### ISSUE TITLE
"insert_final_newline" does not work on ".editorconfig" file

### ISSUE THREAD

**Issue by bennyn** [welovecoding/editorconfig-netbeans#44]
Write this into your `.editorconfig`:

```
root = true

[*.{html,yml}]
charset = utf-8
insert_final_newline = true

[{.editorconfig,.travis.yml}]
indent_style = space
indent_size = 2
insert_final_newline = true
```

Try to save the file. You will see that no final new line will be added and that the file cannot be saved (NetBeans will always show a bold file name in the tab). The file can only be saved if you add a final new line manually, like:

```
root = true

[*.{html,yml}]
charset = utf-8
insert_final_newline = true

[{.editorconfig,.travis.yml}]
indent_style = space
indent_size = 2
insert_final_newline = true

```

**Comment by bennyn** [comment]
I got an error in the IDE logging when trying to save the file. Add final new line was not successful and IDE log showed:

```
INFO [EditorConfigProcessor]: "insert_final_newline": true (Q:/dev/projects/welovecoding/javeasy/.editorconfig)
INFO [FinalNewLineOperation]: ¬ Added final new line
INFO [EditorConfigProcessor]: Flush file changes for: Q:/dev/projects/welovecoding/javeasy/.editorconfig
INFO [EditorConfigProcessor]: Update changes in Editor window for: Q:/dev/projects/welovecoding/javeasy/.editorconfig
INFO [StyledDocumentWriter]: Write to "is": java.io.ByteArrayInputStream@71919d94
INFO [StyledDocumentWriter]: Write to "document": java.io.ByteArrayInputStream@71919d94
SEVERE [global]
java.lang.NullPointerException
	at com.welovecoding.netbeans.plugin.editorconfig.io.writer.StyledDocumentWriter.writeWithEditorKit(StyledDocumentWriter.java:135)
	at com.welovecoding.netbeans.plugin.editorconfig.processor.EditorConfigProcessor.lambda$null$1(EditorConfigProcessor.java:250)
	at com.welovecoding.netbeans.plugin.editorconfig.processor.EditorConfigProcessor$$Lambda$30/1289736729.run(Unknown Source)
	at org.netbeans.editor.GuardedDocument.runAtomic(GuardedDocument.java:323)
	at org.openide.text.NbDocument.runAtomic(NbDocument.java:436)
	at com.welovecoding.netbeans.plugin.editorconfig.processor.EditorConfigProcessor.lambda$updateChangesInEditorWindow$2(EditorConfigProcessor.java:248)
	at com.welovecoding.netbeans.plugin.editorconfig.processor.EditorConfigProcessor$$Lambda$29/876100027.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Yserz** [comment]
I cannot reproduce this. It's working as expected for me.

**Comment by bennyn** [comment]
Plugin works when I run it in the NetBeans Test IDE but in my development IDE it conflicted with another plugin. So that was the issue.

**Comment by Wirone** [comment]
Does not work for me. NetBeans 8.1, JDK 1.8.0_60.

```
; top-most EditorConfig file
root = true

; Unix-style newlines
[*]
end_of_line = LF

[*.{php,json}]
trim_trailing_whitespace = true
indent_style = space
indent_size = 4

[*.php]
insert_final_newline = true

[*.yml]
indent_style = space
indent_size = 2
```

When I save my file final newline is missing. If I add it manually, it is trimmed on save. When I disable EditorConfig plugin it works ok (final new line isn't trimmed).
