### ISSUE TITLE
NullPointerException at FileInfo.getCurrentCaretPosition

### ISSUE THREAD

**Issue by jhavlin** [welovecoding/editorconfig-netbeans#83]
Hello,

this exception has been reported to NetBeans Bugzilla.

Stacktrace: 
```
java.lang.NullPointerException
   at com.welovecoding.nbeditorconfig.processor.FileInfo.getCurrentCaretPosition(FileInfo.java:65)
   at com.welovecoding.nbeditorconfig.processor.operation.TrimTrailingWhiteSpaceOperation.detectCaretOffset(TrimTrailingWhiteSpaceOperation.java:51)
   at com.welovecoding.nbeditorconfig.processor.operation.TrimTrailingWhiteSpaceOperation.operate(TrimTrailingWhiteSpaceOperation.java:30)
   at com.welovecoding.nbeditorconfig.processor.operation.TrimTrailingWhiteSpaceOperation.operate(TrimTrailingWhiteSpaceOperation.java:20)
   at com.welovecoding.nbeditorconfig.processor.EditorConfigProcessor.excuteOperations(EditorConfigProcessor.java:190)
   at com.welovecoding.nbeditorconfig.processor.EditorConfigProcessor.applyRulesToFile(EditorConfigProcessor.java:95)
```

See https://netbeans.org/bugzilla/show_bug.cgi?id=253637.

Please evaluate this bug. Thank you.

**Comment by bennyn** [comment]
@jhavlin, Thank you very much for your report! 
Can you reproduce this issue with [v0.0.8-beta](https://github.com/welovecoding/editorconfig-netbeans/releases/tag/v0.0.8-beta)?

**Comment by Yserz** [comment]
Fixed with [v0.0.8-beta](https://github.com/welovecoding/editorconfig-netbeans/releases/tag/v0.0.8-beta)

**Comment by jhavlin** [comment]
Version 0.0.8-beta seems to work fine.
Thank you very much for the fix.

**Comment by Yserz** [comment]
Great to hear that and thx for reporting :)
